markdown: kramdown
redcarpet:
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "止水"
markdown: kramdown

author: "zhishui"
atom-baseurl: "https://bizhishui.github.io/"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Categories
    class: fa fa-sitemap
    href: /categories.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Links
    class: fa fa-external-link
    href: /links.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

