markdown: kramdown
highlighter: rouge
#permalink: /:year/:month/:day/:title.html
permalink: /:title
name: "止水"
markdown: kramdown

author: "zhishui"
atom-baseurl: "https://bizhishui.github.io/"
#date_format: '%B %d, %Y'
#disqus: "gopherwood"
disqus_shortname: 'bizhishui'

# Post sharing icons
#sharing:
#    twitter: true
#    linkedin: true
#    facebook: true
#    google_plus: true
#    wechat: true

navigations:
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Categories
    class: fa fa-sitemap
    href: /categories.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Links
    class: fa fa-external-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

